/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Traceability } from './Traceability.js';
export * as factories from './factories/index.js';
export { Traceability__factory } from './factories/Traceability__factory.js';