/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface SubsidyPayoutOracleConsumerInterface extends Interface {
    getFunction(nameOrSignature: "autoDistrict" | "autoFarmer" | "autoMetadataHash" | "autoProgramId" | "autoState" | "autoStationId" | "automationCaller" | "donId" | "executeApprovedPayout" | "gasLimit" | "handleOracleFulfillment" | "owner" | "payout" | "pendingRequests" | "performUpkeep" | "requestWaterLevelCheck" | "source" | "subscriptionId" | "updateAutomationCaller" | "updateAutomationConfig" | "updateConfig" | "updateSource"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ApprovedPayoutExecuted" | "AutoClaimCreationFailed" | "AutomationCallerUpdated" | "AutomationConfigUpdated" | "ConfigUpdated" | "OwnerUpdated" | "RequestFulfilled" | "RequestSent" | "SourceUpdated" | "WaterLevelCheckErrored" | "WaterLevelCheckFulfilled" | "WaterLevelCheckRequested"): EventFragment;

    encodeFunctionData(functionFragment: 'autoDistrict', values?: undefined): string;
encodeFunctionData(functionFragment: 'autoFarmer', values?: undefined): string;
encodeFunctionData(functionFragment: 'autoMetadataHash', values?: undefined): string;
encodeFunctionData(functionFragment: 'autoProgramId', values?: undefined): string;
encodeFunctionData(functionFragment: 'autoState', values?: undefined): string;
encodeFunctionData(functionFragment: 'autoStationId', values?: undefined): string;
encodeFunctionData(functionFragment: 'automationCaller', values?: undefined): string;
encodeFunctionData(functionFragment: 'donId', values?: undefined): string;
encodeFunctionData(functionFragment: 'executeApprovedPayout', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'gasLimit', values?: undefined): string;
encodeFunctionData(functionFragment: 'handleOracleFulfillment', values: [BytesLike, BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'payout', values?: undefined): string;
encodeFunctionData(functionFragment: 'pendingRequests', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'performUpkeep', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'requestWaterLevelCheck', values: [BigNumberish, AddressLike, string, string, string, BytesLike]): string;
encodeFunctionData(functionFragment: 'source', values?: undefined): string;
encodeFunctionData(functionFragment: 'subscriptionId', values?: undefined): string;
encodeFunctionData(functionFragment: 'updateAutomationCaller', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updateAutomationConfig', values: [BigNumberish, AddressLike, string, string, string, BytesLike]): string;
encodeFunctionData(functionFragment: 'updateConfig', values: [BigNumberish, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'updateSource', values: [string]): string;

    decodeFunctionResult(functionFragment: 'autoDistrict', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'autoFarmer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'autoMetadataHash', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'autoProgramId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'autoState', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'autoStationId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'automationCaller', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'donId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'executeApprovedPayout', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'gasLimit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'handleOracleFulfillment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'payout', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pendingRequests', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'performUpkeep', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requestWaterLevelCheck', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'source', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'subscriptionId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateAutomationCaller', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateAutomationConfig', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateConfig', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateSource', data: BytesLike): Result;
  }

  
    export namespace ApprovedPayoutExecutedEvent {
      export type InputTuple = [claimId: BigNumberish];
      export type OutputTuple = [claimId: bigint];
      export interface OutputObject {claimId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AutoClaimCreationFailedEvent {
      export type InputTuple = [requestId: BytesLike, programsId: BigNumberish, farmer: AddressLike];
      export type OutputTuple = [requestId: string, programsId: bigint, farmer: string];
      export interface OutputObject {requestId: string, programsId: bigint, farmer: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AutomationCallerUpdatedEvent {
      export type InputTuple = [newCaller: AddressLike];
      export type OutputTuple = [newCaller: string];
      export interface OutputObject {newCaller: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AutomationConfigUpdatedEvent {
      export type InputTuple = [programsId: BigNumberish, farmer: AddressLike, state: string, district: string, stationId: string, metadataHash: BytesLike];
      export type OutputTuple = [programsId: bigint, farmer: string, state: string, district: string, stationId: string, metadataHash: string];
      export interface OutputObject {programsId: bigint, farmer: string, state: string, district: string, stationId: string, metadataHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ConfigUpdatedEvent {
      export type InputTuple = [subscriptionId: BigNumberish, donId: BytesLike, gasLimit: BigNumberish];
      export type OutputTuple = [subscriptionId: bigint, donId: string, gasLimit: bigint];
      export interface OutputObject {subscriptionId: bigint, donId: string, gasLimit: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnerUpdatedEvent {
      export type InputTuple = [newOwner: AddressLike];
      export type OutputTuple = [newOwner: string];
      export interface OutputObject {newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RequestFulfilledEvent {
      export type InputTuple = [id: BytesLike];
      export type OutputTuple = [id: string];
      export interface OutputObject {id: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RequestSentEvent {
      export type InputTuple = [id: BytesLike];
      export type OutputTuple = [id: string];
      export interface OutputObject {id: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SourceUpdatedEvent {
      export type InputTuple = [source: string];
      export type OutputTuple = [source: string];
      export interface OutputObject {source: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WaterLevelCheckErroredEvent {
      export type InputTuple = [requestId: BytesLike, error: BytesLike];
      export type OutputTuple = [requestId: string, error: string];
      export interface OutputObject {requestId: string, error: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WaterLevelCheckFulfilledEvent {
      export type InputTuple = [requestId: BytesLike, programsId: BigNumberish, farmer: AddressLike, state: string, district: string, stationId: string, waterLevelCurrent: BigNumberish, waterLevelDanger: BigNumberish, triggered: boolean, enrolled: boolean, claimId: BigNumberish];
      export type OutputTuple = [requestId: string, programsId: bigint, farmer: string, state: string, district: string, stationId: string, waterLevelCurrent: bigint, waterLevelDanger: bigint, triggered: boolean, enrolled: boolean, claimId: bigint];
      export interface OutputObject {requestId: string, programsId: bigint, farmer: string, state: string, district: string, stationId: string, waterLevelCurrent: bigint, waterLevelDanger: bigint, triggered: boolean, enrolled: boolean, claimId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WaterLevelCheckRequestedEvent {
      export type InputTuple = [requestId: BytesLike, programsId: BigNumberish, farmer: AddressLike, state: string, district: string, stationId: string, metadataHash: BytesLike];
      export type OutputTuple = [requestId: string, programsId: bigint, farmer: string, state: string, district: string, stationId: string, metadataHash: string];
      export interface OutputObject {requestId: string, programsId: bigint, farmer: string, state: string, district: string, stationId: string, metadataHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface SubsidyPayoutOracleConsumer extends BaseContract {
    
    connect(runner?: ContractRunner | null): SubsidyPayoutOracleConsumer;
    waitForDeployment(): Promise<this>;

    interface: SubsidyPayoutOracleConsumerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    autoDistrict: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    autoFarmer: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    autoMetadataHash: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    autoProgramId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    autoState: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    autoStationId: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    automationCaller: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    donId: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    executeApprovedPayout: TypedContractMethod<
      [claimId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    gasLimit: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    handleOracleFulfillment: TypedContractMethod<
      [requestId: BytesLike, response: BytesLike, err: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    payout: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pendingRequests: TypedContractMethod<
      [arg0: BytesLike, ],
      [[bigint, string, string, string, string, string, boolean] & {programsId: bigint, farmer: string, state: string, district: string, stationId: string, metadataHash: string, exists: boolean }],
      'view'
    >
    

    
    performUpkeep: TypedContractMethod<
      [arg0: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    requestWaterLevelCheck: TypedContractMethod<
      [programsId: BigNumberish, farmer: AddressLike, state: string, district: string, stationId: string, metadataHash: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    source: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    subscriptionId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    updateAutomationCaller: TypedContractMethod<
      [newCaller: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateAutomationConfig: TypedContractMethod<
      [programsId: BigNumberish, farmer: AddressLike, state: string, district: string, stationId: string, metadataHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateConfig: TypedContractMethod<
      [functionsSubscriptionId: BigNumberish, functionsDonId: BytesLike, functionsGasLimit: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    updateSource: TypedContractMethod<
      [newSource: string, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'autoDistrict'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'autoFarmer'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'autoMetadataHash'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'autoProgramId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'autoState'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'autoStationId'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'automationCaller'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'donId'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'executeApprovedPayout'): TypedContractMethod<
      [claimId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'gasLimit'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'handleOracleFulfillment'): TypedContractMethod<
      [requestId: BytesLike, response: BytesLike, err: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'payout'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pendingRequests'): TypedContractMethod<
      [arg0: BytesLike, ],
      [[bigint, string, string, string, string, string, boolean] & {programsId: bigint, farmer: string, state: string, district: string, stationId: string, metadataHash: string, exists: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'performUpkeep'): TypedContractMethod<
      [arg0: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'requestWaterLevelCheck'): TypedContractMethod<
      [programsId: BigNumberish, farmer: AddressLike, state: string, district: string, stationId: string, metadataHash: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'source'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'subscriptionId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'updateAutomationCaller'): TypedContractMethod<
      [newCaller: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateAutomationConfig'): TypedContractMethod<
      [programsId: BigNumberish, farmer: AddressLike, state: string, district: string, stationId: string, metadataHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateConfig'): TypedContractMethod<
      [functionsSubscriptionId: BigNumberish, functionsDonId: BytesLike, functionsGasLimit: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateSource'): TypedContractMethod<
      [newSource: string, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ApprovedPayoutExecuted'): TypedContractEvent<ApprovedPayoutExecutedEvent.InputTuple, ApprovedPayoutExecutedEvent.OutputTuple, ApprovedPayoutExecutedEvent.OutputObject>;
getEvent(key: 'AutoClaimCreationFailed'): TypedContractEvent<AutoClaimCreationFailedEvent.InputTuple, AutoClaimCreationFailedEvent.OutputTuple, AutoClaimCreationFailedEvent.OutputObject>;
getEvent(key: 'AutomationCallerUpdated'): TypedContractEvent<AutomationCallerUpdatedEvent.InputTuple, AutomationCallerUpdatedEvent.OutputTuple, AutomationCallerUpdatedEvent.OutputObject>;
getEvent(key: 'AutomationConfigUpdated'): TypedContractEvent<AutomationConfigUpdatedEvent.InputTuple, AutomationConfigUpdatedEvent.OutputTuple, AutomationConfigUpdatedEvent.OutputObject>;
getEvent(key: 'ConfigUpdated'): TypedContractEvent<ConfigUpdatedEvent.InputTuple, ConfigUpdatedEvent.OutputTuple, ConfigUpdatedEvent.OutputObject>;
getEvent(key: 'OwnerUpdated'): TypedContractEvent<OwnerUpdatedEvent.InputTuple, OwnerUpdatedEvent.OutputTuple, OwnerUpdatedEvent.OutputObject>;
getEvent(key: 'RequestFulfilled'): TypedContractEvent<RequestFulfilledEvent.InputTuple, RequestFulfilledEvent.OutputTuple, RequestFulfilledEvent.OutputObject>;
getEvent(key: 'RequestSent'): TypedContractEvent<RequestSentEvent.InputTuple, RequestSentEvent.OutputTuple, RequestSentEvent.OutputObject>;
getEvent(key: 'SourceUpdated'): TypedContractEvent<SourceUpdatedEvent.InputTuple, SourceUpdatedEvent.OutputTuple, SourceUpdatedEvent.OutputObject>;
getEvent(key: 'WaterLevelCheckErrored'): TypedContractEvent<WaterLevelCheckErroredEvent.InputTuple, WaterLevelCheckErroredEvent.OutputTuple, WaterLevelCheckErroredEvent.OutputObject>;
getEvent(key: 'WaterLevelCheckFulfilled'): TypedContractEvent<WaterLevelCheckFulfilledEvent.InputTuple, WaterLevelCheckFulfilledEvent.OutputTuple, WaterLevelCheckFulfilledEvent.OutputObject>;
getEvent(key: 'WaterLevelCheckRequested'): TypedContractEvent<WaterLevelCheckRequestedEvent.InputTuple, WaterLevelCheckRequestedEvent.OutputTuple, WaterLevelCheckRequestedEvent.OutputObject>;

    filters: {
      
      'ApprovedPayoutExecuted(uint256)': TypedContractEvent<ApprovedPayoutExecutedEvent.InputTuple, ApprovedPayoutExecutedEvent.OutputTuple, ApprovedPayoutExecutedEvent.OutputObject>;
      ApprovedPayoutExecuted: TypedContractEvent<ApprovedPayoutExecutedEvent.InputTuple, ApprovedPayoutExecutedEvent.OutputTuple, ApprovedPayoutExecutedEvent.OutputObject>;
    

      'AutoClaimCreationFailed(bytes32,uint256,address)': TypedContractEvent<AutoClaimCreationFailedEvent.InputTuple, AutoClaimCreationFailedEvent.OutputTuple, AutoClaimCreationFailedEvent.OutputObject>;
      AutoClaimCreationFailed: TypedContractEvent<AutoClaimCreationFailedEvent.InputTuple, AutoClaimCreationFailedEvent.OutputTuple, AutoClaimCreationFailedEvent.OutputObject>;
    

      'AutomationCallerUpdated(address)': TypedContractEvent<AutomationCallerUpdatedEvent.InputTuple, AutomationCallerUpdatedEvent.OutputTuple, AutomationCallerUpdatedEvent.OutputObject>;
      AutomationCallerUpdated: TypedContractEvent<AutomationCallerUpdatedEvent.InputTuple, AutomationCallerUpdatedEvent.OutputTuple, AutomationCallerUpdatedEvent.OutputObject>;
    

      'AutomationConfigUpdated(uint256,address,string,string,string,bytes32)': TypedContractEvent<AutomationConfigUpdatedEvent.InputTuple, AutomationConfigUpdatedEvent.OutputTuple, AutomationConfigUpdatedEvent.OutputObject>;
      AutomationConfigUpdated: TypedContractEvent<AutomationConfigUpdatedEvent.InputTuple, AutomationConfigUpdatedEvent.OutputTuple, AutomationConfigUpdatedEvent.OutputObject>;
    

      'ConfigUpdated(uint64,bytes32,uint32)': TypedContractEvent<ConfigUpdatedEvent.InputTuple, ConfigUpdatedEvent.OutputTuple, ConfigUpdatedEvent.OutputObject>;
      ConfigUpdated: TypedContractEvent<ConfigUpdatedEvent.InputTuple, ConfigUpdatedEvent.OutputTuple, ConfigUpdatedEvent.OutputObject>;
    

      'OwnerUpdated(address)': TypedContractEvent<OwnerUpdatedEvent.InputTuple, OwnerUpdatedEvent.OutputTuple, OwnerUpdatedEvent.OutputObject>;
      OwnerUpdated: TypedContractEvent<OwnerUpdatedEvent.InputTuple, OwnerUpdatedEvent.OutputTuple, OwnerUpdatedEvent.OutputObject>;
    

      'RequestFulfilled(bytes32)': TypedContractEvent<RequestFulfilledEvent.InputTuple, RequestFulfilledEvent.OutputTuple, RequestFulfilledEvent.OutputObject>;
      RequestFulfilled: TypedContractEvent<RequestFulfilledEvent.InputTuple, RequestFulfilledEvent.OutputTuple, RequestFulfilledEvent.OutputObject>;
    

      'RequestSent(bytes32)': TypedContractEvent<RequestSentEvent.InputTuple, RequestSentEvent.OutputTuple, RequestSentEvent.OutputObject>;
      RequestSent: TypedContractEvent<RequestSentEvent.InputTuple, RequestSentEvent.OutputTuple, RequestSentEvent.OutputObject>;
    

      'SourceUpdated(string)': TypedContractEvent<SourceUpdatedEvent.InputTuple, SourceUpdatedEvent.OutputTuple, SourceUpdatedEvent.OutputObject>;
      SourceUpdated: TypedContractEvent<SourceUpdatedEvent.InputTuple, SourceUpdatedEvent.OutputTuple, SourceUpdatedEvent.OutputObject>;
    

      'WaterLevelCheckErrored(bytes32,bytes)': TypedContractEvent<WaterLevelCheckErroredEvent.InputTuple, WaterLevelCheckErroredEvent.OutputTuple, WaterLevelCheckErroredEvent.OutputObject>;
      WaterLevelCheckErrored: TypedContractEvent<WaterLevelCheckErroredEvent.InputTuple, WaterLevelCheckErroredEvent.OutputTuple, WaterLevelCheckErroredEvent.OutputObject>;
    

      'WaterLevelCheckFulfilled(bytes32,uint256,address,string,string,string,uint256,uint256,bool,bool,uint256)': TypedContractEvent<WaterLevelCheckFulfilledEvent.InputTuple, WaterLevelCheckFulfilledEvent.OutputTuple, WaterLevelCheckFulfilledEvent.OutputObject>;
      WaterLevelCheckFulfilled: TypedContractEvent<WaterLevelCheckFulfilledEvent.InputTuple, WaterLevelCheckFulfilledEvent.OutputTuple, WaterLevelCheckFulfilledEvent.OutputObject>;
    

      'WaterLevelCheckRequested(bytes32,uint256,address,string,string,string,bytes32)': TypedContractEvent<WaterLevelCheckRequestedEvent.InputTuple, WaterLevelCheckRequestedEvent.OutputTuple, WaterLevelCheckRequestedEvent.OutputObject>;
      WaterLevelCheckRequested: TypedContractEvent<WaterLevelCheckRequestedEvent.InputTuple, WaterLevelCheckRequestedEvent.OutputTuple, WaterLevelCheckRequestedEvent.OutputObject>;
    
    };
  }