/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface SubsidyPayoutOracleConsumerInterface extends Interface {
    getFunction(nameOrSignature: "donId" | "gasLimit" | "handleOracleFulfillment" | "owner" | "payout" | "pendingRequests" | "requestFloodCheck" | "source" | "subscriptionId" | "updateConfig" | "updateSource"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ConfigUpdated" | "FloodCheckErrored" | "FloodCheckFulfilled" | "FloodCheckRequested" | "OwnerUpdated" | "RequestFulfilled" | "RequestSent" | "SourceUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'donId', values?: undefined): string;
encodeFunctionData(functionFragment: 'gasLimit', values?: undefined): string;
encodeFunctionData(functionFragment: 'handleOracleFulfillment', values: [BytesLike, BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'payout', values?: undefined): string;
encodeFunctionData(functionFragment: 'pendingRequests', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'requestFloodCheck', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'source', values?: undefined): string;
encodeFunctionData(functionFragment: 'subscriptionId', values?: undefined): string;
encodeFunctionData(functionFragment: 'updateConfig', values: [BigNumberish, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'updateSource', values: [string]): string;

    decodeFunctionResult(functionFragment: 'donId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'gasLimit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'handleOracleFulfillment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'payout', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pendingRequests', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requestFloodCheck', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'source', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'subscriptionId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateConfig', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateSource', data: BytesLike): Result;
  }

  
    export namespace ConfigUpdatedEvent {
      export type InputTuple = [subscriptionId: BigNumberish, donId: BytesLike, gasLimit: BigNumberish];
      export type OutputTuple = [subscriptionId: bigint, donId: string, gasLimit: bigint];
      export interface OutputObject {subscriptionId: bigint, donId: string, gasLimit: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FloodCheckErroredEvent {
      export type InputTuple = [requestId: BytesLike, error: BytesLike];
      export type OutputTuple = [requestId: string, error: string];
      export interface OutputObject {requestId: string, error: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FloodCheckFulfilledEvent {
      export type InputTuple = [requestId: BytesLike, rainfallMm: BigNumberish, triggered: boolean];
      export type OutputTuple = [requestId: string, rainfallMm: bigint, triggered: boolean];
      export interface OutputObject {requestId: string, rainfallMm: bigint, triggered: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FloodCheckRequestedEvent {
      export type InputTuple = [requestId: BytesLike, policyId: BigNumberish, claimId: BigNumberish, thresholdMm: BigNumberish];
      export type OutputTuple = [requestId: string, policyId: bigint, claimId: bigint, thresholdMm: bigint];
      export interface OutputObject {requestId: string, policyId: bigint, claimId: bigint, thresholdMm: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnerUpdatedEvent {
      export type InputTuple = [newOwner: AddressLike];
      export type OutputTuple = [newOwner: string];
      export interface OutputObject {newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RequestFulfilledEvent {
      export type InputTuple = [id: BytesLike];
      export type OutputTuple = [id: string];
      export interface OutputObject {id: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RequestSentEvent {
      export type InputTuple = [id: BytesLike];
      export type OutputTuple = [id: string];
      export interface OutputObject {id: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SourceUpdatedEvent {
      export type InputTuple = [source: string];
      export type OutputTuple = [source: string];
      export interface OutputObject {source: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface SubsidyPayoutOracleConsumer extends BaseContract {
    
    connect(runner?: ContractRunner | null): SubsidyPayoutOracleConsumer;
    waitForDeployment(): Promise<this>;

    interface: SubsidyPayoutOracleConsumerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    donId: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    gasLimit: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    handleOracleFulfillment: TypedContractMethod<
      [requestId: BytesLike, response: BytesLike, err: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    payout: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pendingRequests: TypedContractMethod<
      [arg0: BytesLike, ],
      [[bigint, bigint, bigint, boolean] & {policyId: bigint, claimId: bigint, thresholdMm: bigint, exists: boolean }],
      'view'
    >
    

    
    requestFloodCheck: TypedContractMethod<
      [policyId: BigNumberish, claimId: BigNumberish, thresholdMm: BigNumberish, ],
      [string],
      'nonpayable'
    >
    

    
    source: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    subscriptionId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    updateConfig: TypedContractMethod<
      [functionsSubscriptionId: BigNumberish, functionsDonId: BytesLike, functionsGasLimit: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    updateSource: TypedContractMethod<
      [newSource: string, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'donId'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'gasLimit'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'handleOracleFulfillment'): TypedContractMethod<
      [requestId: BytesLike, response: BytesLike, err: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'payout'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pendingRequests'): TypedContractMethod<
      [arg0: BytesLike, ],
      [[bigint, bigint, bigint, boolean] & {policyId: bigint, claimId: bigint, thresholdMm: bigint, exists: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'requestFloodCheck'): TypedContractMethod<
      [policyId: BigNumberish, claimId: BigNumberish, thresholdMm: BigNumberish, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'source'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'subscriptionId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'updateConfig'): TypedContractMethod<
      [functionsSubscriptionId: BigNumberish, functionsDonId: BytesLike, functionsGasLimit: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateSource'): TypedContractMethod<
      [newSource: string, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ConfigUpdated'): TypedContractEvent<ConfigUpdatedEvent.InputTuple, ConfigUpdatedEvent.OutputTuple, ConfigUpdatedEvent.OutputObject>;
getEvent(key: 'FloodCheckErrored'): TypedContractEvent<FloodCheckErroredEvent.InputTuple, FloodCheckErroredEvent.OutputTuple, FloodCheckErroredEvent.OutputObject>;
getEvent(key: 'FloodCheckFulfilled'): TypedContractEvent<FloodCheckFulfilledEvent.InputTuple, FloodCheckFulfilledEvent.OutputTuple, FloodCheckFulfilledEvent.OutputObject>;
getEvent(key: 'FloodCheckRequested'): TypedContractEvent<FloodCheckRequestedEvent.InputTuple, FloodCheckRequestedEvent.OutputTuple, FloodCheckRequestedEvent.OutputObject>;
getEvent(key: 'OwnerUpdated'): TypedContractEvent<OwnerUpdatedEvent.InputTuple, OwnerUpdatedEvent.OutputTuple, OwnerUpdatedEvent.OutputObject>;
getEvent(key: 'RequestFulfilled'): TypedContractEvent<RequestFulfilledEvent.InputTuple, RequestFulfilledEvent.OutputTuple, RequestFulfilledEvent.OutputObject>;
getEvent(key: 'RequestSent'): TypedContractEvent<RequestSentEvent.InputTuple, RequestSentEvent.OutputTuple, RequestSentEvent.OutputObject>;
getEvent(key: 'SourceUpdated'): TypedContractEvent<SourceUpdatedEvent.InputTuple, SourceUpdatedEvent.OutputTuple, SourceUpdatedEvent.OutputObject>;

    filters: {
      
      'ConfigUpdated(uint64,bytes32,uint32)': TypedContractEvent<ConfigUpdatedEvent.InputTuple, ConfigUpdatedEvent.OutputTuple, ConfigUpdatedEvent.OutputObject>;
      ConfigUpdated: TypedContractEvent<ConfigUpdatedEvent.InputTuple, ConfigUpdatedEvent.OutputTuple, ConfigUpdatedEvent.OutputObject>;
    

      'FloodCheckErrored(bytes32,bytes)': TypedContractEvent<FloodCheckErroredEvent.InputTuple, FloodCheckErroredEvent.OutputTuple, FloodCheckErroredEvent.OutputObject>;
      FloodCheckErrored: TypedContractEvent<FloodCheckErroredEvent.InputTuple, FloodCheckErroredEvent.OutputTuple, FloodCheckErroredEvent.OutputObject>;
    

      'FloodCheckFulfilled(bytes32,uint256,bool)': TypedContractEvent<FloodCheckFulfilledEvent.InputTuple, FloodCheckFulfilledEvent.OutputTuple, FloodCheckFulfilledEvent.OutputObject>;
      FloodCheckFulfilled: TypedContractEvent<FloodCheckFulfilledEvent.InputTuple, FloodCheckFulfilledEvent.OutputTuple, FloodCheckFulfilledEvent.OutputObject>;
    

      'FloodCheckRequested(bytes32,uint256,uint256,uint256)': TypedContractEvent<FloodCheckRequestedEvent.InputTuple, FloodCheckRequestedEvent.OutputTuple, FloodCheckRequestedEvent.OutputObject>;
      FloodCheckRequested: TypedContractEvent<FloodCheckRequestedEvent.InputTuple, FloodCheckRequestedEvent.OutputTuple, FloodCheckRequestedEvent.OutputObject>;
    

      'OwnerUpdated(address)': TypedContractEvent<OwnerUpdatedEvent.InputTuple, OwnerUpdatedEvent.OutputTuple, OwnerUpdatedEvent.OutputObject>;
      OwnerUpdated: TypedContractEvent<OwnerUpdatedEvent.InputTuple, OwnerUpdatedEvent.OutputTuple, OwnerUpdatedEvent.OutputObject>;
    

      'RequestFulfilled(bytes32)': TypedContractEvent<RequestFulfilledEvent.InputTuple, RequestFulfilledEvent.OutputTuple, RequestFulfilledEvent.OutputObject>;
      RequestFulfilled: TypedContractEvent<RequestFulfilledEvent.InputTuple, RequestFulfilledEvent.OutputTuple, RequestFulfilledEvent.OutputObject>;
    

      'RequestSent(bytes32)': TypedContractEvent<RequestSentEvent.InputTuple, RequestSentEvent.OutputTuple, RequestSentEvent.OutputObject>;
      RequestSent: TypedContractEvent<RequestSentEvent.InputTuple, RequestSentEvent.OutputTuple, RequestSentEvent.OutputObject>;
    

      'SourceUpdated(string)': TypedContractEvent<SourceUpdatedEvent.InputTuple, SourceUpdatedEvent.OutputTuple, SourceUpdatedEvent.OutputObject>;
      SourceUpdated: TypedContractEvent<SourceUpdatedEvent.InputTuple, SourceUpdatedEvent.OutputTuple, SourceUpdatedEvent.OutputObject>;
    
    };
  }