/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace SubsidyPayout {
      
    export type PayoutRuleStruct = {amount: BigNumberish, maxCap: BigNumberish}

    export type PayoutRuleStructOutput = [amount: bigint, maxCap: bigint] & {amount: bigint, maxCap: bigint }
  

    export type EligibilityStruct = {hasMinFarmSize: boolean, hasMaxFarmSize: boolean, minFarmSize: BigNumberish, maxFarmSize: BigNumberish, states: string[], districts: string[], cropTypes: string[], certifications: string[]}

    export type EligibilityStructOutput = [hasMinFarmSize: boolean, hasMaxFarmSize: boolean, minFarmSize: bigint, maxFarmSize: bigint, states: string[], districts: string[], cropTypes: string[], certifications: string[]] & {hasMinFarmSize: boolean, hasMaxFarmSize: boolean, minFarmSize: bigint, maxFarmSize: bigint, states: string[], districts: string[], cropTypes: string[], certifications: string[] }
  

    export type ClaimStruct = {policyId: BigNumberish, farmer: AddressLike, amount: BigNumberish, status: BigNumberish, metadataHash: BytesLike, submittedAt: BigNumberish, rejectionReason: string}

    export type ClaimStructOutput = [policyId: bigint, farmer: string, amount: bigint, status: bigint, metadataHash: string, submittedAt: bigint, rejectionReason: string] & {policyId: bigint, farmer: string, amount: bigint, status: bigint, metadataHash: string, submittedAt: bigint, rejectionReason: string }
  

    export type PolicyStruct = {name: string, description: string, policyType: BigNumberish, status: BigNumberish, startDate: BigNumberish, endDate: BigNumberish, createdBy: string, metadataHash: BytesLike, payoutRule: SubsidyPayout.PayoutRuleStruct, eligibility: SubsidyPayout.EligibilityStruct, totalDisbursed: BigNumberish}

    export type PolicyStructOutput = [name: string, description: string, policyType: bigint, status: bigint, startDate: bigint, endDate: bigint, createdBy: string, metadataHash: string, payoutRule: SubsidyPayout.PayoutRuleStructOutput, eligibility: SubsidyPayout.EligibilityStructOutput, totalDisbursed: bigint] & {name: string, description: string, policyType: bigint, status: bigint, startDate: bigint, endDate: bigint, createdBy: string, metadataHash: string, payoutRule: SubsidyPayout.PayoutRuleStructOutput, eligibility: SubsidyPayout.EligibilityStructOutput, totalDisbursed: bigint }
  
    }

  export interface SubsidyPayoutInterface extends Interface {
    getFunction(nameOrSignature: "approveAndPayout" | "approveClaim" | "autoCreateClaim" | "claims" | "createPolicy" | "deposit" | "enrollInPolicy" | "enrolledPolicies" | "getClaim" | "getPolicy" | "grantGovernmentRole" | "isFarmerEnrolled" | "isGovernment" | "nextClaimId" | "nextPolicyId" | "oracle" | "owner" | "policies" | "rejectClaim" | "revokeGovernmentRole" | "submitClaim" | "updateEligibility" | "updateOracle" | "updateOwner" | "updatePayoutRule" | "updatePolicyStatus"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AutoClaimCreated" | "ClaimApproved" | "ClaimPaid" | "ClaimRejected" | "ClaimSubmitted" | "EligibilityUpdated" | "FarmerEnrolled" | "FundsDeposited" | "GovernmentRoleGranted" | "GovernmentRoleRevoked" | "OracleUpdated" | "OwnerUpdated" | "PolicyCreated" | "PolicyStatusUpdated" | "PolicyUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'approveAndPayout', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'approveClaim', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'autoCreateClaim', values: [BigNumberish, AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'claims', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createPolicy', values: [string, string, BigNumberish, BigNumberish, BigNumberish, BigNumberish, string, BytesLike, SubsidyPayout.PayoutRuleStruct, SubsidyPayout.EligibilityStruct]): string;
encodeFunctionData(functionFragment: 'deposit', values?: undefined): string;
encodeFunctionData(functionFragment: 'enrollInPolicy', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'enrolledPolicies', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getClaim', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getPolicy', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'grantGovernmentRole', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isFarmerEnrolled', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'isGovernment', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'nextClaimId', values?: undefined): string;
encodeFunctionData(functionFragment: 'nextPolicyId', values?: undefined): string;
encodeFunctionData(functionFragment: 'oracle', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'policies', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'rejectClaim', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'revokeGovernmentRole', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'submitClaim', values: [BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'updateEligibility', values: [BigNumberish, SubsidyPayout.EligibilityStruct]): string;
encodeFunctionData(functionFragment: 'updateOracle', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updateOwner', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updatePayoutRule', values: [BigNumberish, SubsidyPayout.PayoutRuleStruct]): string;
encodeFunctionData(functionFragment: 'updatePolicyStatus', values: [BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'approveAndPayout', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approveClaim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'autoCreateClaim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claims', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createPolicy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'enrollInPolicy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'enrolledPolicies', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getClaim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPolicy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantGovernmentRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isFarmerEnrolled', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isGovernment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextClaimId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextPolicyId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'oracle', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'policies', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rejectClaim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeGovernmentRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitClaim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateEligibility', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateOracle', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updatePayoutRule', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updatePolicyStatus', data: BytesLike): Result;
  }

  
    export namespace AutoClaimCreatedEvent {
      export type InputTuple = [claimId: BigNumberish, policyId: BigNumberish, farmer: AddressLike];
      export type OutputTuple = [claimId: bigint, policyId: bigint, farmer: string];
      export interface OutputObject {claimId: bigint, policyId: bigint, farmer: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ClaimApprovedEvent {
      export type InputTuple = [claimId: BigNumberish, policyId: BigNumberish, farmer: AddressLike, amount: BigNumberish];
      export type OutputTuple = [claimId: bigint, policyId: bigint, farmer: string, amount: bigint];
      export interface OutputObject {claimId: bigint, policyId: bigint, farmer: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ClaimPaidEvent {
      export type InputTuple = [claimId: BigNumberish, policyId: BigNumberish, farmer: AddressLike, amount: BigNumberish];
      export type OutputTuple = [claimId: bigint, policyId: bigint, farmer: string, amount: bigint];
      export interface OutputObject {claimId: bigint, policyId: bigint, farmer: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ClaimRejectedEvent {
      export type InputTuple = [claimId: BigNumberish, policyId: BigNumberish, farmer: AddressLike, reason: string];
      export type OutputTuple = [claimId: bigint, policyId: bigint, farmer: string, reason: string];
      export interface OutputObject {claimId: bigint, policyId: bigint, farmer: string, reason: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ClaimSubmittedEvent {
      export type InputTuple = [claimId: BigNumberish, policyId: BigNumberish, farmer: AddressLike, amount: BigNumberish, metadataHash: BytesLike];
      export type OutputTuple = [claimId: bigint, policyId: bigint, farmer: string, amount: bigint, metadataHash: string];
      export interface OutputObject {claimId: bigint, policyId: bigint, farmer: string, amount: bigint, metadataHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EligibilityUpdatedEvent {
      export type InputTuple = [policyId: BigNumberish];
      export type OutputTuple = [policyId: bigint];
      export interface OutputObject {policyId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FarmerEnrolledEvent {
      export type InputTuple = [farmer: AddressLike, policyId: BigNumberish];
      export type OutputTuple = [farmer: string, policyId: bigint];
      export interface OutputObject {farmer: string, policyId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FundsDepositedEvent {
      export type InputTuple = [from: AddressLike, amount: BigNumberish];
      export type OutputTuple = [from: string, amount: bigint];
      export interface OutputObject {from: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace GovernmentRoleGrantedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace GovernmentRoleRevokedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OracleUpdatedEvent {
      export type InputTuple = [oracle: AddressLike];
      export type OutputTuple = [oracle: string];
      export interface OutputObject {oracle: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnerUpdatedEvent {
      export type InputTuple = [owner: AddressLike];
      export type OutputTuple = [owner: string];
      export interface OutputObject {owner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PolicyCreatedEvent {
      export type InputTuple = [policyId: BigNumberish, name: string, policyType: BigNumberish, status: BigNumberish, startDate: BigNumberish, endDate: BigNumberish, metadataHash: BytesLike, payoutAmount: BigNumberish, payoutMaxCap: BigNumberish];
      export type OutputTuple = [policyId: bigint, name: string, policyType: bigint, status: bigint, startDate: bigint, endDate: bigint, metadataHash: string, payoutAmount: bigint, payoutMaxCap: bigint];
      export interface OutputObject {policyId: bigint, name: string, policyType: bigint, status: bigint, startDate: bigint, endDate: bigint, metadataHash: string, payoutAmount: bigint, payoutMaxCap: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PolicyStatusUpdatedEvent {
      export type InputTuple = [policyId: BigNumberish, status: BigNumberish];
      export type OutputTuple = [policyId: bigint, status: bigint];
      export interface OutputObject {policyId: bigint, status: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PolicyUpdatedEvent {
      export type InputTuple = [policyId: BigNumberish, payoutAmount: BigNumberish, payoutMaxCap: BigNumberish];
      export type OutputTuple = [policyId: bigint, payoutAmount: bigint, payoutMaxCap: bigint];
      export interface OutputObject {policyId: bigint, payoutAmount: bigint, payoutMaxCap: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface SubsidyPayout extends BaseContract {
    
    connect(runner?: ContractRunner | null): SubsidyPayout;
    waitForDeployment(): Promise<this>;

    interface: SubsidyPayoutInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    approveAndPayout: TypedContractMethod<
      [claimId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    approveClaim: TypedContractMethod<
      [claimId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    autoCreateClaim: TypedContractMethod<
      [policyId: BigNumberish, farmer: AddressLike, metadataHash: BytesLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    claims: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, bigint, bigint, string, bigint, string] & {policyId: bigint, farmer: string, amount: bigint, status: bigint, metadataHash: string, submittedAt: bigint, rejectionReason: string }],
      'view'
    >
    

    
    createPolicy: TypedContractMethod<
      [name: string, description: string, policyType: BigNumberish, status: BigNumberish, startDate: BigNumberish, endDate: BigNumberish, createdBy: string, metadataHash: BytesLike, payoutRule: SubsidyPayout.PayoutRuleStruct, eligibility: SubsidyPayout.EligibilityStruct, ],
      [bigint],
      'nonpayable'
    >
    

    
    deposit: TypedContractMethod<
      [],
      [void],
      'payable'
    >
    

    
    enrollInPolicy: TypedContractMethod<
      [policyId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    enrolledPolicies: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getClaim: TypedContractMethod<
      [claimId: BigNumberish, ],
      [SubsidyPayout.ClaimStructOutput],
      'view'
    >
    

    
    getPolicy: TypedContractMethod<
      [policyId: BigNumberish, ],
      [SubsidyPayout.PolicyStructOutput],
      'view'
    >
    

    
    grantGovernmentRole: TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    isFarmerEnrolled: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isGovernment: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    nextClaimId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    nextPolicyId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    oracle: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    policies: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, bigint, bigint, bigint, string, string, SubsidyPayout.PayoutRuleStructOutput, SubsidyPayout.EligibilityStructOutput, bigint] & {name: string, description: string, policyType: bigint, status: bigint, startDate: bigint, endDate: bigint, createdBy: string, metadataHash: string, payoutRule: SubsidyPayout.PayoutRuleStructOutput, eligibility: SubsidyPayout.EligibilityStructOutput, totalDisbursed: bigint }],
      'view'
    >
    

    
    rejectClaim: TypedContractMethod<
      [claimId: BigNumberish, reason: string, ],
      [void],
      'nonpayable'
    >
    

    
    revokeGovernmentRole: TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    submitClaim: TypedContractMethod<
      [policyId: BigNumberish, metadataHash: BytesLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    updateEligibility: TypedContractMethod<
      [policyId: BigNumberish, eligibility: SubsidyPayout.EligibilityStruct, ],
      [void],
      'nonpayable'
    >
    

    
    updateOracle: TypedContractMethod<
      [newOracle: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateOwner: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updatePayoutRule: TypedContractMethod<
      [policyId: BigNumberish, payoutRule: SubsidyPayout.PayoutRuleStruct, ],
      [void],
      'nonpayable'
    >
    

    
    updatePolicyStatus: TypedContractMethod<
      [policyId: BigNumberish, status: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'approveAndPayout'): TypedContractMethod<
      [claimId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'approveClaim'): TypedContractMethod<
      [claimId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'autoCreateClaim'): TypedContractMethod<
      [policyId: BigNumberish, farmer: AddressLike, metadataHash: BytesLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claims'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, bigint, bigint, string, bigint, string] & {policyId: bigint, farmer: string, amount: bigint, status: bigint, metadataHash: string, submittedAt: bigint, rejectionReason: string }],
      'view'
    >;
getFunction(nameOrSignature: 'createPolicy'): TypedContractMethod<
      [name: string, description: string, policyType: BigNumberish, status: BigNumberish, startDate: BigNumberish, endDate: BigNumberish, createdBy: string, metadataHash: BytesLike, payoutRule: SubsidyPayout.PayoutRuleStruct, eligibility: SubsidyPayout.EligibilityStruct, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'deposit'): TypedContractMethod<
      [],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'enrollInPolicy'): TypedContractMethod<
      [policyId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'enrolledPolicies'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getClaim'): TypedContractMethod<
      [claimId: BigNumberish, ],
      [SubsidyPayout.ClaimStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getPolicy'): TypedContractMethod<
      [policyId: BigNumberish, ],
      [SubsidyPayout.PolicyStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'grantGovernmentRole'): TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'isFarmerEnrolled'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isGovernment'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'nextClaimId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'nextPolicyId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'oracle'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'policies'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, bigint, bigint, bigint, string, string, SubsidyPayout.PayoutRuleStructOutput, SubsidyPayout.EligibilityStructOutput, bigint] & {name: string, description: string, policyType: bigint, status: bigint, startDate: bigint, endDate: bigint, createdBy: string, metadataHash: string, payoutRule: SubsidyPayout.PayoutRuleStructOutput, eligibility: SubsidyPayout.EligibilityStructOutput, totalDisbursed: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'rejectClaim'): TypedContractMethod<
      [claimId: BigNumberish, reason: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeGovernmentRole'): TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submitClaim'): TypedContractMethod<
      [policyId: BigNumberish, metadataHash: BytesLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateEligibility'): TypedContractMethod<
      [policyId: BigNumberish, eligibility: SubsidyPayout.EligibilityStruct, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateOracle'): TypedContractMethod<
      [newOracle: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateOwner'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updatePayoutRule'): TypedContractMethod<
      [policyId: BigNumberish, payoutRule: SubsidyPayout.PayoutRuleStruct, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updatePolicyStatus'): TypedContractMethod<
      [policyId: BigNumberish, status: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AutoClaimCreated'): TypedContractEvent<AutoClaimCreatedEvent.InputTuple, AutoClaimCreatedEvent.OutputTuple, AutoClaimCreatedEvent.OutputObject>;
getEvent(key: 'ClaimApproved'): TypedContractEvent<ClaimApprovedEvent.InputTuple, ClaimApprovedEvent.OutputTuple, ClaimApprovedEvent.OutputObject>;
getEvent(key: 'ClaimPaid'): TypedContractEvent<ClaimPaidEvent.InputTuple, ClaimPaidEvent.OutputTuple, ClaimPaidEvent.OutputObject>;
getEvent(key: 'ClaimRejected'): TypedContractEvent<ClaimRejectedEvent.InputTuple, ClaimRejectedEvent.OutputTuple, ClaimRejectedEvent.OutputObject>;
getEvent(key: 'ClaimSubmitted'): TypedContractEvent<ClaimSubmittedEvent.InputTuple, ClaimSubmittedEvent.OutputTuple, ClaimSubmittedEvent.OutputObject>;
getEvent(key: 'EligibilityUpdated'): TypedContractEvent<EligibilityUpdatedEvent.InputTuple, EligibilityUpdatedEvent.OutputTuple, EligibilityUpdatedEvent.OutputObject>;
getEvent(key: 'FarmerEnrolled'): TypedContractEvent<FarmerEnrolledEvent.InputTuple, FarmerEnrolledEvent.OutputTuple, FarmerEnrolledEvent.OutputObject>;
getEvent(key: 'FundsDeposited'): TypedContractEvent<FundsDepositedEvent.InputTuple, FundsDepositedEvent.OutputTuple, FundsDepositedEvent.OutputObject>;
getEvent(key: 'GovernmentRoleGranted'): TypedContractEvent<GovernmentRoleGrantedEvent.InputTuple, GovernmentRoleGrantedEvent.OutputTuple, GovernmentRoleGrantedEvent.OutputObject>;
getEvent(key: 'GovernmentRoleRevoked'): TypedContractEvent<GovernmentRoleRevokedEvent.InputTuple, GovernmentRoleRevokedEvent.OutputTuple, GovernmentRoleRevokedEvent.OutputObject>;
getEvent(key: 'OracleUpdated'): TypedContractEvent<OracleUpdatedEvent.InputTuple, OracleUpdatedEvent.OutputTuple, OracleUpdatedEvent.OutputObject>;
getEvent(key: 'OwnerUpdated'): TypedContractEvent<OwnerUpdatedEvent.InputTuple, OwnerUpdatedEvent.OutputTuple, OwnerUpdatedEvent.OutputObject>;
getEvent(key: 'PolicyCreated'): TypedContractEvent<PolicyCreatedEvent.InputTuple, PolicyCreatedEvent.OutputTuple, PolicyCreatedEvent.OutputObject>;
getEvent(key: 'PolicyStatusUpdated'): TypedContractEvent<PolicyStatusUpdatedEvent.InputTuple, PolicyStatusUpdatedEvent.OutputTuple, PolicyStatusUpdatedEvent.OutputObject>;
getEvent(key: 'PolicyUpdated'): TypedContractEvent<PolicyUpdatedEvent.InputTuple, PolicyUpdatedEvent.OutputTuple, PolicyUpdatedEvent.OutputObject>;

    filters: {
      
      'AutoClaimCreated(uint256,uint256,address)': TypedContractEvent<AutoClaimCreatedEvent.InputTuple, AutoClaimCreatedEvent.OutputTuple, AutoClaimCreatedEvent.OutputObject>;
      AutoClaimCreated: TypedContractEvent<AutoClaimCreatedEvent.InputTuple, AutoClaimCreatedEvent.OutputTuple, AutoClaimCreatedEvent.OutputObject>;
    

      'ClaimApproved(uint256,uint256,address,uint256)': TypedContractEvent<ClaimApprovedEvent.InputTuple, ClaimApprovedEvent.OutputTuple, ClaimApprovedEvent.OutputObject>;
      ClaimApproved: TypedContractEvent<ClaimApprovedEvent.InputTuple, ClaimApprovedEvent.OutputTuple, ClaimApprovedEvent.OutputObject>;
    

      'ClaimPaid(uint256,uint256,address,uint256)': TypedContractEvent<ClaimPaidEvent.InputTuple, ClaimPaidEvent.OutputTuple, ClaimPaidEvent.OutputObject>;
      ClaimPaid: TypedContractEvent<ClaimPaidEvent.InputTuple, ClaimPaidEvent.OutputTuple, ClaimPaidEvent.OutputObject>;
    

      'ClaimRejected(uint256,uint256,address,string)': TypedContractEvent<ClaimRejectedEvent.InputTuple, ClaimRejectedEvent.OutputTuple, ClaimRejectedEvent.OutputObject>;
      ClaimRejected: TypedContractEvent<ClaimRejectedEvent.InputTuple, ClaimRejectedEvent.OutputTuple, ClaimRejectedEvent.OutputObject>;
    

      'ClaimSubmitted(uint256,uint256,address,uint256,bytes32)': TypedContractEvent<ClaimSubmittedEvent.InputTuple, ClaimSubmittedEvent.OutputTuple, ClaimSubmittedEvent.OutputObject>;
      ClaimSubmitted: TypedContractEvent<ClaimSubmittedEvent.InputTuple, ClaimSubmittedEvent.OutputTuple, ClaimSubmittedEvent.OutputObject>;
    

      'EligibilityUpdated(uint256)': TypedContractEvent<EligibilityUpdatedEvent.InputTuple, EligibilityUpdatedEvent.OutputTuple, EligibilityUpdatedEvent.OutputObject>;
      EligibilityUpdated: TypedContractEvent<EligibilityUpdatedEvent.InputTuple, EligibilityUpdatedEvent.OutputTuple, EligibilityUpdatedEvent.OutputObject>;
    

      'FarmerEnrolled(address,uint256)': TypedContractEvent<FarmerEnrolledEvent.InputTuple, FarmerEnrolledEvent.OutputTuple, FarmerEnrolledEvent.OutputObject>;
      FarmerEnrolled: TypedContractEvent<FarmerEnrolledEvent.InputTuple, FarmerEnrolledEvent.OutputTuple, FarmerEnrolledEvent.OutputObject>;
    

      'FundsDeposited(address,uint256)': TypedContractEvent<FundsDepositedEvent.InputTuple, FundsDepositedEvent.OutputTuple, FundsDepositedEvent.OutputObject>;
      FundsDeposited: TypedContractEvent<FundsDepositedEvent.InputTuple, FundsDepositedEvent.OutputTuple, FundsDepositedEvent.OutputObject>;
    

      'GovernmentRoleGranted(address)': TypedContractEvent<GovernmentRoleGrantedEvent.InputTuple, GovernmentRoleGrantedEvent.OutputTuple, GovernmentRoleGrantedEvent.OutputObject>;
      GovernmentRoleGranted: TypedContractEvent<GovernmentRoleGrantedEvent.InputTuple, GovernmentRoleGrantedEvent.OutputTuple, GovernmentRoleGrantedEvent.OutputObject>;
    

      'GovernmentRoleRevoked(address)': TypedContractEvent<GovernmentRoleRevokedEvent.InputTuple, GovernmentRoleRevokedEvent.OutputTuple, GovernmentRoleRevokedEvent.OutputObject>;
      GovernmentRoleRevoked: TypedContractEvent<GovernmentRoleRevokedEvent.InputTuple, GovernmentRoleRevokedEvent.OutputTuple, GovernmentRoleRevokedEvent.OutputObject>;
    

      'OracleUpdated(address)': TypedContractEvent<OracleUpdatedEvent.InputTuple, OracleUpdatedEvent.OutputTuple, OracleUpdatedEvent.OutputObject>;
      OracleUpdated: TypedContractEvent<OracleUpdatedEvent.InputTuple, OracleUpdatedEvent.OutputTuple, OracleUpdatedEvent.OutputObject>;
    

      'OwnerUpdated(address)': TypedContractEvent<OwnerUpdatedEvent.InputTuple, OwnerUpdatedEvent.OutputTuple, OwnerUpdatedEvent.OutputObject>;
      OwnerUpdated: TypedContractEvent<OwnerUpdatedEvent.InputTuple, OwnerUpdatedEvent.OutputTuple, OwnerUpdatedEvent.OutputObject>;
    

      'PolicyCreated(uint256,string,uint8,uint8,uint256,uint256,bytes32,uint256,uint256)': TypedContractEvent<PolicyCreatedEvent.InputTuple, PolicyCreatedEvent.OutputTuple, PolicyCreatedEvent.OutputObject>;
      PolicyCreated: TypedContractEvent<PolicyCreatedEvent.InputTuple, PolicyCreatedEvent.OutputTuple, PolicyCreatedEvent.OutputObject>;
    

      'PolicyStatusUpdated(uint256,uint8)': TypedContractEvent<PolicyStatusUpdatedEvent.InputTuple, PolicyStatusUpdatedEvent.OutputTuple, PolicyStatusUpdatedEvent.OutputObject>;
      PolicyStatusUpdated: TypedContractEvent<PolicyStatusUpdatedEvent.InputTuple, PolicyStatusUpdatedEvent.OutputTuple, PolicyStatusUpdatedEvent.OutputObject>;
    

      'PolicyUpdated(uint256,uint256,uint256)': TypedContractEvent<PolicyUpdatedEvent.InputTuple, PolicyUpdatedEvent.OutputTuple, PolicyUpdatedEvent.OutputObject>;
      PolicyUpdated: TypedContractEvent<PolicyUpdatedEvent.InputTuple, PolicyUpdatedEvent.OutputTuple, PolicyUpdatedEvent.OutputObject>;
    
    };
  }