/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace SubsidyPayout {
      
    export type PayoutRuleStruct = {amount: BigNumberish, maxCap: BigNumberish}

    export type PayoutRuleStructOutput = [amount: bigint, maxCap: bigint] & {amount: bigint, maxCap: bigint }
  

    export type EligibilityStruct = {hasMinFarmSize: boolean, hasMaxFarmSize: boolean, minFarmSize: BigNumberish, maxFarmSize: BigNumberish, states: string[], districts: string[], cropTypes: string[], certifications: string[]}

    export type EligibilityStructOutput = [hasMinFarmSize: boolean, hasMaxFarmSize: boolean, minFarmSize: bigint, maxFarmSize: bigint, states: string[], districts: string[], cropTypes: string[], certifications: string[]] & {hasMinFarmSize: boolean, hasMaxFarmSize: boolean, minFarmSize: bigint, maxFarmSize: bigint, states: string[], districts: string[], cropTypes: string[], certifications: string[] }
  

    export type ClaimStruct = {programsId: BigNumberish, farmer: AddressLike, amount: BigNumberish, status: BigNumberish, metadataHash: BytesLike, submittedAt: BigNumberish, rejectionReason: string}

    export type ClaimStructOutput = [programsId: bigint, farmer: string, amount: bigint, status: bigint, metadataHash: string, submittedAt: bigint, rejectionReason: string] & {programsId: bigint, farmer: string, amount: bigint, status: bigint, metadataHash: string, submittedAt: bigint, rejectionReason: string }
  

    export type ProgramStruct = {name: string, description: string, programsType: BigNumberish, status: BigNumberish, startDate: BigNumberish, endDate: BigNumberish, createdBy: string, metadataHash: BytesLike, payoutRule: SubsidyPayout.PayoutRuleStruct, eligibility: SubsidyPayout.EligibilityStruct, totalDisbursed: BigNumberish}

    export type ProgramStructOutput = [name: string, description: string, programsType: bigint, status: bigint, startDate: bigint, endDate: bigint, createdBy: string, metadataHash: string, payoutRule: SubsidyPayout.PayoutRuleStructOutput, eligibility: SubsidyPayout.EligibilityStructOutput, totalDisbursed: bigint] & {name: string, description: string, programsType: bigint, status: bigint, startDate: bigint, endDate: bigint, createdBy: string, metadataHash: string, payoutRule: SubsidyPayout.PayoutRuleStructOutput, eligibility: SubsidyPayout.EligibilityStructOutput, totalDisbursed: bigint }
  
    }

  export interface SubsidyPayoutInterface extends Interface {
    getFunction(nameOrSignature: "agencyFunds" | "approveAndPayout" | "approveClaim" | "autoCreateClaim" | "claims" | "createProgram" | "deposit" | "disburseClaim" | "enrollInProgram" | "enrolledPrograms" | "getAgencyBalance" | "getClaim" | "getProgram" | "grantGovernmentRole" | "isFarmerEnrolled" | "isGovernment" | "nextClaimId" | "nextProgramId" | "oracle" | "owner" | "programs" | "rejectClaim" | "revokeGovernmentRole" | "submitClaim" | "updateEligibility" | "updateOracle" | "updateOwner" | "updatePayoutRule" | "updateProgramStatus"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AutoClaimCreated" | "ClaimApproved" | "ClaimDisbursed" | "ClaimPaid" | "ClaimRejected" | "ClaimSubmitted" | "ContractFunded" | "EligibilityUpdated" | "FarmerEnrolled" | "FundsDeposited" | "GovernmentRoleGranted" | "GovernmentRoleRevoked" | "OracleUpdated" | "OwnerUpdated" | "ProgramCreated" | "ProgramStatusUpdated" | "ProgramUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'agencyFunds', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'approveAndPayout', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'approveClaim', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'autoCreateClaim', values: [BigNumberish, AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'claims', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createProgram', values: [string, string, BigNumberish, BigNumberish, BigNumberish, BigNumberish, string, BytesLike, SubsidyPayout.PayoutRuleStruct, SubsidyPayout.EligibilityStruct]): string;
encodeFunctionData(functionFragment: 'deposit', values?: undefined): string;
encodeFunctionData(functionFragment: 'disburseClaim', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'enrollInProgram', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'enrolledPrograms', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAgencyBalance', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getClaim', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getProgram', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'grantGovernmentRole', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isFarmerEnrolled', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'isGovernment', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'nextClaimId', values?: undefined): string;
encodeFunctionData(functionFragment: 'nextProgramId', values?: undefined): string;
encodeFunctionData(functionFragment: 'oracle', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'programs', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'rejectClaim', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'revokeGovernmentRole', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'submitClaim', values: [BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'updateEligibility', values: [BigNumberish, SubsidyPayout.EligibilityStruct]): string;
encodeFunctionData(functionFragment: 'updateOracle', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updateOwner', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updatePayoutRule', values: [BigNumberish, SubsidyPayout.PayoutRuleStruct]): string;
encodeFunctionData(functionFragment: 'updateProgramStatus', values: [BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'agencyFunds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approveAndPayout', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approveClaim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'autoCreateClaim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claims', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createProgram', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'disburseClaim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'enrollInProgram', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'enrolledPrograms', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAgencyBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getClaim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProgram', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantGovernmentRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isFarmerEnrolled', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isGovernment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextClaimId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextProgramId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'oracle', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'programs', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rejectClaim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeGovernmentRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitClaim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateEligibility', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateOracle', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updatePayoutRule', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateProgramStatus', data: BytesLike): Result;
  }

  
    export namespace AutoClaimCreatedEvent {
      export type InputTuple = [claimId: BigNumberish, programsId: BigNumberish, farmer: AddressLike];
      export type OutputTuple = [claimId: bigint, programsId: bigint, farmer: string];
      export interface OutputObject {claimId: bigint, programsId: bigint, farmer: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ClaimApprovedEvent {
      export type InputTuple = [claimId: BigNumberish, programsId: BigNumberish, farmer: AddressLike, amount: BigNumberish];
      export type OutputTuple = [claimId: bigint, programsId: bigint, farmer: string, amount: bigint];
      export interface OutputObject {claimId: bigint, programsId: bigint, farmer: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ClaimDisbursedEvent {
      export type InputTuple = [claimId: BigNumberish, programsId: BigNumberish, farmer: AddressLike, amount: BigNumberish];
      export type OutputTuple = [claimId: bigint, programsId: bigint, farmer: string, amount: bigint];
      export interface OutputObject {claimId: bigint, programsId: bigint, farmer: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ClaimPaidEvent {
      export type InputTuple = [claimId: BigNumberish, programsId: BigNumberish, farmer: AddressLike, amount: BigNumberish];
      export type OutputTuple = [claimId: bigint, programsId: bigint, farmer: string, amount: bigint];
      export interface OutputObject {claimId: bigint, programsId: bigint, farmer: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ClaimRejectedEvent {
      export type InputTuple = [claimId: BigNumberish, programsId: BigNumberish, farmer: AddressLike, reason: string];
      export type OutputTuple = [claimId: bigint, programsId: bigint, farmer: string, reason: string];
      export interface OutputObject {claimId: bigint, programsId: bigint, farmer: string, reason: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ClaimSubmittedEvent {
      export type InputTuple = [claimId: BigNumberish, programsId: BigNumberish, farmer: AddressLike, amount: BigNumberish, metadataHash: BytesLike];
      export type OutputTuple = [claimId: bigint, programsId: bigint, farmer: string, amount: bigint, metadataHash: string];
      export interface OutputObject {claimId: bigint, programsId: bigint, farmer: string, amount: bigint, metadataHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ContractFundedEvent {
      export type InputTuple = [agency: AddressLike, amount: BigNumberish];
      export type OutputTuple = [agency: string, amount: bigint];
      export interface OutputObject {agency: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EligibilityUpdatedEvent {
      export type InputTuple = [programsId: BigNumberish];
      export type OutputTuple = [programsId: bigint];
      export interface OutputObject {programsId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FarmerEnrolledEvent {
      export type InputTuple = [farmer: AddressLike, programsId: BigNumberish];
      export type OutputTuple = [farmer: string, programsId: bigint];
      export interface OutputObject {farmer: string, programsId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FundsDepositedEvent {
      export type InputTuple = [from: AddressLike, amount: BigNumberish];
      export type OutputTuple = [from: string, amount: bigint];
      export interface OutputObject {from: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace GovernmentRoleGrantedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace GovernmentRoleRevokedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OracleUpdatedEvent {
      export type InputTuple = [oracle: AddressLike];
      export type OutputTuple = [oracle: string];
      export interface OutputObject {oracle: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnerUpdatedEvent {
      export type InputTuple = [owner: AddressLike];
      export type OutputTuple = [owner: string];
      export interface OutputObject {owner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProgramCreatedEvent {
      export type InputTuple = [programsId: BigNumberish, name: string, programsType: BigNumberish, status: BigNumberish, startDate: BigNumberish, endDate: BigNumberish, metadataHash: BytesLike, payoutAmount: BigNumberish, payoutMaxCap: BigNumberish];
      export type OutputTuple = [programsId: bigint, name: string, programsType: bigint, status: bigint, startDate: bigint, endDate: bigint, metadataHash: string, payoutAmount: bigint, payoutMaxCap: bigint];
      export interface OutputObject {programsId: bigint, name: string, programsType: bigint, status: bigint, startDate: bigint, endDate: bigint, metadataHash: string, payoutAmount: bigint, payoutMaxCap: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProgramStatusUpdatedEvent {
      export type InputTuple = [programsId: BigNumberish, status: BigNumberish];
      export type OutputTuple = [programsId: bigint, status: bigint];
      export interface OutputObject {programsId: bigint, status: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProgramUpdatedEvent {
      export type InputTuple = [programsId: BigNumberish, payoutAmount: BigNumberish, payoutMaxCap: BigNumberish];
      export type OutputTuple = [programsId: bigint, payoutAmount: bigint, payoutMaxCap: bigint];
      export interface OutputObject {programsId: bigint, payoutAmount: bigint, payoutMaxCap: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface SubsidyPayout extends BaseContract {
    
    connect(runner?: ContractRunner | null): SubsidyPayout;
    waitForDeployment(): Promise<this>;

    interface: SubsidyPayoutInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    agencyFunds: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    approveAndPayout: TypedContractMethod<
      [claimId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    approveClaim: TypedContractMethod<
      [claimId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    autoCreateClaim: TypedContractMethod<
      [programsId: BigNumberish, farmer: AddressLike, metadataHash: BytesLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    claims: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, bigint, bigint, string, bigint, string] & {programsId: bigint, farmer: string, amount: bigint, status: bigint, metadataHash: string, submittedAt: bigint, rejectionReason: string }],
      'view'
    >
    

    
    createProgram: TypedContractMethod<
      [name: string, description: string, programsType: BigNumberish, status: BigNumberish, startDate: BigNumberish, endDate: BigNumberish, createdBy: string, metadataHash: BytesLike, payoutRule: SubsidyPayout.PayoutRuleStruct, eligibility: SubsidyPayout.EligibilityStruct, ],
      [bigint],
      'nonpayable'
    >
    

    
    deposit: TypedContractMethod<
      [],
      [void],
      'payable'
    >
    

    
    disburseClaim: TypedContractMethod<
      [claimId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    enrollInProgram: TypedContractMethod<
      [programsId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    enrolledPrograms: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getAgencyBalance: TypedContractMethod<
      [agency: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getClaim: TypedContractMethod<
      [claimId: BigNumberish, ],
      [SubsidyPayout.ClaimStructOutput],
      'view'
    >
    

    
    getProgram: TypedContractMethod<
      [programsId: BigNumberish, ],
      [SubsidyPayout.ProgramStructOutput],
      'view'
    >
    

    
    grantGovernmentRole: TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    isFarmerEnrolled: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isGovernment: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    nextClaimId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    nextProgramId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    oracle: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    programs: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, bigint, bigint, bigint, string, string, SubsidyPayout.PayoutRuleStructOutput, SubsidyPayout.EligibilityStructOutput, bigint] & {name: string, description: string, programsType: bigint, status: bigint, startDate: bigint, endDate: bigint, createdBy: string, metadataHash: string, payoutRule: SubsidyPayout.PayoutRuleStructOutput, eligibility: SubsidyPayout.EligibilityStructOutput, totalDisbursed: bigint }],
      'view'
    >
    

    
    rejectClaim: TypedContractMethod<
      [claimId: BigNumberish, reason: string, ],
      [void],
      'nonpayable'
    >
    

    
    revokeGovernmentRole: TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    submitClaim: TypedContractMethod<
      [programsId: BigNumberish, metadataHash: BytesLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    updateEligibility: TypedContractMethod<
      [programsId: BigNumberish, eligibility: SubsidyPayout.EligibilityStruct, ],
      [void],
      'nonpayable'
    >
    

    
    updateOracle: TypedContractMethod<
      [newOracle: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateOwner: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updatePayoutRule: TypedContractMethod<
      [programsId: BigNumberish, payoutRule: SubsidyPayout.PayoutRuleStruct, ],
      [void],
      'nonpayable'
    >
    

    
    updateProgramStatus: TypedContractMethod<
      [programsId: BigNumberish, status: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'agencyFunds'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'approveAndPayout'): TypedContractMethod<
      [claimId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'approveClaim'): TypedContractMethod<
      [claimId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'autoCreateClaim'): TypedContractMethod<
      [programsId: BigNumberish, farmer: AddressLike, metadataHash: BytesLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claims'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, bigint, bigint, string, bigint, string] & {programsId: bigint, farmer: string, amount: bigint, status: bigint, metadataHash: string, submittedAt: bigint, rejectionReason: string }],
      'view'
    >;
getFunction(nameOrSignature: 'createProgram'): TypedContractMethod<
      [name: string, description: string, programsType: BigNumberish, status: BigNumberish, startDate: BigNumberish, endDate: BigNumberish, createdBy: string, metadataHash: BytesLike, payoutRule: SubsidyPayout.PayoutRuleStruct, eligibility: SubsidyPayout.EligibilityStruct, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'deposit'): TypedContractMethod<
      [],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'disburseClaim'): TypedContractMethod<
      [claimId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'enrollInProgram'): TypedContractMethod<
      [programsId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'enrolledPrograms'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getAgencyBalance'): TypedContractMethod<
      [agency: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getClaim'): TypedContractMethod<
      [claimId: BigNumberish, ],
      [SubsidyPayout.ClaimStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getProgram'): TypedContractMethod<
      [programsId: BigNumberish, ],
      [SubsidyPayout.ProgramStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'grantGovernmentRole'): TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'isFarmerEnrolled'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isGovernment'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'nextClaimId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'nextProgramId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'oracle'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'programs'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, bigint, bigint, bigint, string, string, SubsidyPayout.PayoutRuleStructOutput, SubsidyPayout.EligibilityStructOutput, bigint] & {name: string, description: string, programsType: bigint, status: bigint, startDate: bigint, endDate: bigint, createdBy: string, metadataHash: string, payoutRule: SubsidyPayout.PayoutRuleStructOutput, eligibility: SubsidyPayout.EligibilityStructOutput, totalDisbursed: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'rejectClaim'): TypedContractMethod<
      [claimId: BigNumberish, reason: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeGovernmentRole'): TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submitClaim'): TypedContractMethod<
      [programsId: BigNumberish, metadataHash: BytesLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateEligibility'): TypedContractMethod<
      [programsId: BigNumberish, eligibility: SubsidyPayout.EligibilityStruct, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateOracle'): TypedContractMethod<
      [newOracle: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateOwner'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updatePayoutRule'): TypedContractMethod<
      [programsId: BigNumberish, payoutRule: SubsidyPayout.PayoutRuleStruct, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateProgramStatus'): TypedContractMethod<
      [programsId: BigNumberish, status: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AutoClaimCreated'): TypedContractEvent<AutoClaimCreatedEvent.InputTuple, AutoClaimCreatedEvent.OutputTuple, AutoClaimCreatedEvent.OutputObject>;
getEvent(key: 'ClaimApproved'): TypedContractEvent<ClaimApprovedEvent.InputTuple, ClaimApprovedEvent.OutputTuple, ClaimApprovedEvent.OutputObject>;
getEvent(key: 'ClaimDisbursed'): TypedContractEvent<ClaimDisbursedEvent.InputTuple, ClaimDisbursedEvent.OutputTuple, ClaimDisbursedEvent.OutputObject>;
getEvent(key: 'ClaimPaid'): TypedContractEvent<ClaimPaidEvent.InputTuple, ClaimPaidEvent.OutputTuple, ClaimPaidEvent.OutputObject>;
getEvent(key: 'ClaimRejected'): TypedContractEvent<ClaimRejectedEvent.InputTuple, ClaimRejectedEvent.OutputTuple, ClaimRejectedEvent.OutputObject>;
getEvent(key: 'ClaimSubmitted'): TypedContractEvent<ClaimSubmittedEvent.InputTuple, ClaimSubmittedEvent.OutputTuple, ClaimSubmittedEvent.OutputObject>;
getEvent(key: 'ContractFunded'): TypedContractEvent<ContractFundedEvent.InputTuple, ContractFundedEvent.OutputTuple, ContractFundedEvent.OutputObject>;
getEvent(key: 'EligibilityUpdated'): TypedContractEvent<EligibilityUpdatedEvent.InputTuple, EligibilityUpdatedEvent.OutputTuple, EligibilityUpdatedEvent.OutputObject>;
getEvent(key: 'FarmerEnrolled'): TypedContractEvent<FarmerEnrolledEvent.InputTuple, FarmerEnrolledEvent.OutputTuple, FarmerEnrolledEvent.OutputObject>;
getEvent(key: 'FundsDeposited'): TypedContractEvent<FundsDepositedEvent.InputTuple, FundsDepositedEvent.OutputTuple, FundsDepositedEvent.OutputObject>;
getEvent(key: 'GovernmentRoleGranted'): TypedContractEvent<GovernmentRoleGrantedEvent.InputTuple, GovernmentRoleGrantedEvent.OutputTuple, GovernmentRoleGrantedEvent.OutputObject>;
getEvent(key: 'GovernmentRoleRevoked'): TypedContractEvent<GovernmentRoleRevokedEvent.InputTuple, GovernmentRoleRevokedEvent.OutputTuple, GovernmentRoleRevokedEvent.OutputObject>;
getEvent(key: 'OracleUpdated'): TypedContractEvent<OracleUpdatedEvent.InputTuple, OracleUpdatedEvent.OutputTuple, OracleUpdatedEvent.OutputObject>;
getEvent(key: 'OwnerUpdated'): TypedContractEvent<OwnerUpdatedEvent.InputTuple, OwnerUpdatedEvent.OutputTuple, OwnerUpdatedEvent.OutputObject>;
getEvent(key: 'ProgramCreated'): TypedContractEvent<ProgramCreatedEvent.InputTuple, ProgramCreatedEvent.OutputTuple, ProgramCreatedEvent.OutputObject>;
getEvent(key: 'ProgramStatusUpdated'): TypedContractEvent<ProgramStatusUpdatedEvent.InputTuple, ProgramStatusUpdatedEvent.OutputTuple, ProgramStatusUpdatedEvent.OutputObject>;
getEvent(key: 'ProgramUpdated'): TypedContractEvent<ProgramUpdatedEvent.InputTuple, ProgramUpdatedEvent.OutputTuple, ProgramUpdatedEvent.OutputObject>;

    filters: {
      
      'AutoClaimCreated(uint256,uint256,address)': TypedContractEvent<AutoClaimCreatedEvent.InputTuple, AutoClaimCreatedEvent.OutputTuple, AutoClaimCreatedEvent.OutputObject>;
      AutoClaimCreated: TypedContractEvent<AutoClaimCreatedEvent.InputTuple, AutoClaimCreatedEvent.OutputTuple, AutoClaimCreatedEvent.OutputObject>;
    

      'ClaimApproved(uint256,uint256,address,uint256)': TypedContractEvent<ClaimApprovedEvent.InputTuple, ClaimApprovedEvent.OutputTuple, ClaimApprovedEvent.OutputObject>;
      ClaimApproved: TypedContractEvent<ClaimApprovedEvent.InputTuple, ClaimApprovedEvent.OutputTuple, ClaimApprovedEvent.OutputObject>;
    

      'ClaimDisbursed(uint256,uint256,address,uint256)': TypedContractEvent<ClaimDisbursedEvent.InputTuple, ClaimDisbursedEvent.OutputTuple, ClaimDisbursedEvent.OutputObject>;
      ClaimDisbursed: TypedContractEvent<ClaimDisbursedEvent.InputTuple, ClaimDisbursedEvent.OutputTuple, ClaimDisbursedEvent.OutputObject>;
    

      'ClaimPaid(uint256,uint256,address,uint256)': TypedContractEvent<ClaimPaidEvent.InputTuple, ClaimPaidEvent.OutputTuple, ClaimPaidEvent.OutputObject>;
      ClaimPaid: TypedContractEvent<ClaimPaidEvent.InputTuple, ClaimPaidEvent.OutputTuple, ClaimPaidEvent.OutputObject>;
    

      'ClaimRejected(uint256,uint256,address,string)': TypedContractEvent<ClaimRejectedEvent.InputTuple, ClaimRejectedEvent.OutputTuple, ClaimRejectedEvent.OutputObject>;
      ClaimRejected: TypedContractEvent<ClaimRejectedEvent.InputTuple, ClaimRejectedEvent.OutputTuple, ClaimRejectedEvent.OutputObject>;
    

      'ClaimSubmitted(uint256,uint256,address,uint256,bytes32)': TypedContractEvent<ClaimSubmittedEvent.InputTuple, ClaimSubmittedEvent.OutputTuple, ClaimSubmittedEvent.OutputObject>;
      ClaimSubmitted: TypedContractEvent<ClaimSubmittedEvent.InputTuple, ClaimSubmittedEvent.OutputTuple, ClaimSubmittedEvent.OutputObject>;
    

      'ContractFunded(address,uint256)': TypedContractEvent<ContractFundedEvent.InputTuple, ContractFundedEvent.OutputTuple, ContractFundedEvent.OutputObject>;
      ContractFunded: TypedContractEvent<ContractFundedEvent.InputTuple, ContractFundedEvent.OutputTuple, ContractFundedEvent.OutputObject>;
    

      'EligibilityUpdated(uint256)': TypedContractEvent<EligibilityUpdatedEvent.InputTuple, EligibilityUpdatedEvent.OutputTuple, EligibilityUpdatedEvent.OutputObject>;
      EligibilityUpdated: TypedContractEvent<EligibilityUpdatedEvent.InputTuple, EligibilityUpdatedEvent.OutputTuple, EligibilityUpdatedEvent.OutputObject>;
    

      'FarmerEnrolled(address,uint256)': TypedContractEvent<FarmerEnrolledEvent.InputTuple, FarmerEnrolledEvent.OutputTuple, FarmerEnrolledEvent.OutputObject>;
      FarmerEnrolled: TypedContractEvent<FarmerEnrolledEvent.InputTuple, FarmerEnrolledEvent.OutputTuple, FarmerEnrolledEvent.OutputObject>;
    

      'FundsDeposited(address,uint256)': TypedContractEvent<FundsDepositedEvent.InputTuple, FundsDepositedEvent.OutputTuple, FundsDepositedEvent.OutputObject>;
      FundsDeposited: TypedContractEvent<FundsDepositedEvent.InputTuple, FundsDepositedEvent.OutputTuple, FundsDepositedEvent.OutputObject>;
    

      'GovernmentRoleGranted(address)': TypedContractEvent<GovernmentRoleGrantedEvent.InputTuple, GovernmentRoleGrantedEvent.OutputTuple, GovernmentRoleGrantedEvent.OutputObject>;
      GovernmentRoleGranted: TypedContractEvent<GovernmentRoleGrantedEvent.InputTuple, GovernmentRoleGrantedEvent.OutputTuple, GovernmentRoleGrantedEvent.OutputObject>;
    

      'GovernmentRoleRevoked(address)': TypedContractEvent<GovernmentRoleRevokedEvent.InputTuple, GovernmentRoleRevokedEvent.OutputTuple, GovernmentRoleRevokedEvent.OutputObject>;
      GovernmentRoleRevoked: TypedContractEvent<GovernmentRoleRevokedEvent.InputTuple, GovernmentRoleRevokedEvent.OutputTuple, GovernmentRoleRevokedEvent.OutputObject>;
    

      'OracleUpdated(address)': TypedContractEvent<OracleUpdatedEvent.InputTuple, OracleUpdatedEvent.OutputTuple, OracleUpdatedEvent.OutputObject>;
      OracleUpdated: TypedContractEvent<OracleUpdatedEvent.InputTuple, OracleUpdatedEvent.OutputTuple, OracleUpdatedEvent.OutputObject>;
    

      'OwnerUpdated(address)': TypedContractEvent<OwnerUpdatedEvent.InputTuple, OwnerUpdatedEvent.OutputTuple, OwnerUpdatedEvent.OutputObject>;
      OwnerUpdated: TypedContractEvent<OwnerUpdatedEvent.InputTuple, OwnerUpdatedEvent.OutputTuple, OwnerUpdatedEvent.OutputObject>;
    

      'ProgramCreated(uint256,string,uint8,uint8,uint256,uint256,bytes32,uint256,uint256)': TypedContractEvent<ProgramCreatedEvent.InputTuple, ProgramCreatedEvent.OutputTuple, ProgramCreatedEvent.OutputObject>;
      ProgramCreated: TypedContractEvent<ProgramCreatedEvent.InputTuple, ProgramCreatedEvent.OutputTuple, ProgramCreatedEvent.OutputObject>;
    

      'ProgramStatusUpdated(uint256,uint8)': TypedContractEvent<ProgramStatusUpdatedEvent.InputTuple, ProgramStatusUpdatedEvent.OutputTuple, ProgramStatusUpdatedEvent.OutputObject>;
      ProgramStatusUpdated: TypedContractEvent<ProgramStatusUpdatedEvent.InputTuple, ProgramStatusUpdatedEvent.OutputTuple, ProgramStatusUpdatedEvent.OutputObject>;
    

      'ProgramUpdated(uint256,uint256,uint256)': TypedContractEvent<ProgramUpdatedEvent.InputTuple, ProgramUpdatedEvent.OutputTuple, ProgramUpdatedEvent.OutputObject>;
      ProgramUpdated: TypedContractEvent<ProgramUpdatedEvent.InputTuple, ProgramUpdatedEvent.OutputTuple, ProgramUpdatedEvent.OutputObject>;
    
    };
  }