/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace SubsidyPayout {
      
    export type TriggerStruct = {parameter: string, operator: BigNumberish, threshold: BigNumberish, windowValue: BigNumberish, windowUnit: BigNumberish}

    export type TriggerStructOutput = [parameter: string, operator: bigint, threshold: bigint, windowValue: bigint, windowUnit: bigint] & {parameter: string, operator: bigint, threshold: bigint, windowValue: bigint, windowUnit: bigint }
  

    export type PayoutRuleStruct = {amount: BigNumberish, maxCap: BigNumberish, frequency: BigNumberish, beneficiaryCategory: BigNumberish}

    export type PayoutRuleStructOutput = [amount: bigint, maxCap: bigint, frequency: bigint, beneficiaryCategory: bigint] & {amount: bigint, maxCap: bigint, frequency: bigint, beneficiaryCategory: bigint }
  

    export type EligibilityStruct = {hasMinFarmSize: boolean, hasMaxFarmSize: boolean, minFarmSize: BigNumberish, maxFarmSize: BigNumberish, states: string[], districts: string[], cropTypes: string[], certifications: string[]}

    export type EligibilityStructOutput = [hasMinFarmSize: boolean, hasMaxFarmSize: boolean, minFarmSize: bigint, maxFarmSize: bigint, states: string[], districts: string[], cropTypes: string[], certifications: string[]] & {hasMinFarmSize: boolean, hasMaxFarmSize: boolean, minFarmSize: bigint, maxFarmSize: bigint, states: string[], districts: string[], cropTypes: string[], certifications: string[] }
  

    export type ClaimStruct = {policyId: BigNumberish, farmer: AddressLike, amount: BigNumberish, status: BigNumberish, metadataHash: string, submittedAt: BigNumberish, rejectionReason: string}

    export type ClaimStructOutput = [policyId: bigint, farmer: string, amount: bigint, status: bigint, metadataHash: string, submittedAt: bigint, rejectionReason: string] & {policyId: bigint, farmer: string, amount: bigint, status: bigint, metadataHash: string, submittedAt: bigint, rejectionReason: string }
  

    export type PolicyStruct = {name: string, description: string, policyType: BigNumberish, status: BigNumberish, startDate: BigNumberish, endDate: BigNumberish, createdBy: string, payoutRule: SubsidyPayout.PayoutRuleStruct, eligibility: SubsidyPayout.EligibilityStruct, totalDisbursed: BigNumberish}

    export type PolicyStructOutput = [name: string, description: string, policyType: bigint, status: bigint, startDate: bigint, endDate: bigint, createdBy: string, payoutRule: SubsidyPayout.PayoutRuleStructOutput, eligibility: SubsidyPayout.EligibilityStructOutput, totalDisbursed: bigint] & {name: string, description: string, policyType: bigint, status: bigint, startDate: bigint, endDate: bigint, createdBy: string, payoutRule: SubsidyPayout.PayoutRuleStructOutput, eligibility: SubsidyPayout.EligibilityStructOutput, totalDisbursed: bigint }
  
    }

  export interface SubsidyPayoutInterface extends Interface {
    getFunction(nameOrSignature: "addTrigger" | "approveAndPayout" | "claims" | "clearTriggers" | "createPolicy" | "deposit" | "getClaim" | "getPolicy" | "getTriggers" | "nextClaimId" | "nextPolicyId" | "oracle" | "owner" | "policies" | "recordTriggerHit" | "rejectClaim" | "submitClaim" | "updateEligibility" | "updateOracle" | "updateOwner" | "updatePayoutRule" | "updatePolicyStatus"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ClaimApproved" | "ClaimRejected" | "ClaimSubmitted" | "EligibilityUpdated" | "FundsDeposited" | "OracleUpdated" | "OwnerUpdated" | "PolicyCreated" | "PolicyStatusUpdated" | "PolicyUpdated" | "TriggerAdded" | "TriggerRecorded" | "TriggersCleared"): EventFragment;

    encodeFunctionData(functionFragment: 'addTrigger', values: [BigNumberish, SubsidyPayout.TriggerStruct]): string;
encodeFunctionData(functionFragment: 'approveAndPayout', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'claims', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'clearTriggers', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createPolicy', values: [string, string, BigNumberish, BigNumberish, BigNumberish, BigNumberish, string, SubsidyPayout.PayoutRuleStruct, SubsidyPayout.EligibilityStruct]): string;
encodeFunctionData(functionFragment: 'deposit', values?: undefined): string;
encodeFunctionData(functionFragment: 'getClaim', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getPolicy', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getTriggers', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'nextClaimId', values?: undefined): string;
encodeFunctionData(functionFragment: 'nextPolicyId', values?: undefined): string;
encodeFunctionData(functionFragment: 'oracle', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'policies', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'recordTriggerHit', values: [BigNumberish, string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'rejectClaim', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'submitClaim', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'updateEligibility', values: [BigNumberish, SubsidyPayout.EligibilityStruct]): string;
encodeFunctionData(functionFragment: 'updateOracle', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updateOwner', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updatePayoutRule', values: [BigNumberish, SubsidyPayout.PayoutRuleStruct]): string;
encodeFunctionData(functionFragment: 'updatePolicyStatus', values: [BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'addTrigger', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approveAndPayout', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claims', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'clearTriggers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createPolicy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getClaim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPolicy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTriggers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextClaimId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextPolicyId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'oracle', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'policies', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordTriggerHit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rejectClaim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitClaim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateEligibility', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateOracle', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updatePayoutRule', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updatePolicyStatus', data: BytesLike): Result;
  }

  
    export namespace ClaimApprovedEvent {
      export type InputTuple = [claimId: BigNumberish, policyId: BigNumberish, farmer: AddressLike, amount: BigNumberish];
      export type OutputTuple = [claimId: bigint, policyId: bigint, farmer: string, amount: bigint];
      export interface OutputObject {claimId: bigint, policyId: bigint, farmer: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ClaimRejectedEvent {
      export type InputTuple = [claimId: BigNumberish, policyId: BigNumberish, farmer: AddressLike, reason: string];
      export type OutputTuple = [claimId: bigint, policyId: bigint, farmer: string, reason: string];
      export interface OutputObject {claimId: bigint, policyId: bigint, farmer: string, reason: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ClaimSubmittedEvent {
      export type InputTuple = [claimId: BigNumberish, policyId: BigNumberish, farmer: AddressLike, amount: BigNumberish, metadataHash: string];
      export type OutputTuple = [claimId: bigint, policyId: bigint, farmer: string, amount: bigint, metadataHash: string];
      export interface OutputObject {claimId: bigint, policyId: bigint, farmer: string, amount: bigint, metadataHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EligibilityUpdatedEvent {
      export type InputTuple = [policyId: BigNumberish];
      export type OutputTuple = [policyId: bigint];
      export interface OutputObject {policyId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FundsDepositedEvent {
      export type InputTuple = [from: AddressLike, amount: BigNumberish];
      export type OutputTuple = [from: string, amount: bigint];
      export interface OutputObject {from: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OracleUpdatedEvent {
      export type InputTuple = [oracle: AddressLike];
      export type OutputTuple = [oracle: string];
      export interface OutputObject {oracle: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnerUpdatedEvent {
      export type InputTuple = [owner: AddressLike];
      export type OutputTuple = [owner: string];
      export interface OutputObject {owner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PolicyCreatedEvent {
      export type InputTuple = [policyId: BigNumberish, name: string, policyType: BigNumberish, status: BigNumberish, startDate: BigNumberish, endDate: BigNumberish, payoutAmount: BigNumberish, payoutMaxCap: BigNumberish, frequency: BigNumberish, beneficiaryCategory: BigNumberish];
      export type OutputTuple = [policyId: bigint, name: string, policyType: bigint, status: bigint, startDate: bigint, endDate: bigint, payoutAmount: bigint, payoutMaxCap: bigint, frequency: bigint, beneficiaryCategory: bigint];
      export interface OutputObject {policyId: bigint, name: string, policyType: bigint, status: bigint, startDate: bigint, endDate: bigint, payoutAmount: bigint, payoutMaxCap: bigint, frequency: bigint, beneficiaryCategory: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PolicyStatusUpdatedEvent {
      export type InputTuple = [policyId: BigNumberish, status: BigNumberish];
      export type OutputTuple = [policyId: bigint, status: bigint];
      export interface OutputObject {policyId: bigint, status: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PolicyUpdatedEvent {
      export type InputTuple = [policyId: BigNumberish, payoutAmount: BigNumberish, payoutMaxCap: BigNumberish, frequency: BigNumberish, beneficiaryCategory: BigNumberish];
      export type OutputTuple = [policyId: bigint, payoutAmount: bigint, payoutMaxCap: bigint, frequency: bigint, beneficiaryCategory: bigint];
      export interface OutputObject {policyId: bigint, payoutAmount: bigint, payoutMaxCap: bigint, frequency: bigint, beneficiaryCategory: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TriggerAddedEvent {
      export type InputTuple = [policyId: BigNumberish, parameter: string, operatorValue: BigNumberish, threshold: BigNumberish, windowValue: BigNumberish, windowUnit: BigNumberish];
      export type OutputTuple = [policyId: bigint, parameter: string, operatorValue: bigint, threshold: bigint, windowValue: bigint, windowUnit: bigint];
      export interface OutputObject {policyId: bigint, parameter: string, operatorValue: bigint, threshold: bigint, windowValue: bigint, windowUnit: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TriggerRecordedEvent {
      export type InputTuple = [policyId: BigNumberish, eventId: string, observedValue: BigNumberish];
      export type OutputTuple = [policyId: bigint, eventId: string, observedValue: bigint];
      export interface OutputObject {policyId: bigint, eventId: string, observedValue: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TriggersClearedEvent {
      export type InputTuple = [policyId: BigNumberish];
      export type OutputTuple = [policyId: bigint];
      export interface OutputObject {policyId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface SubsidyPayout extends BaseContract {
    
    connect(runner?: ContractRunner | null): SubsidyPayout;
    waitForDeployment(): Promise<this>;

    interface: SubsidyPayoutInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addTrigger: TypedContractMethod<
      [policyId: BigNumberish, trigger_: SubsidyPayout.TriggerStruct, ],
      [void],
      'nonpayable'
    >
    

    
    approveAndPayout: TypedContractMethod<
      [claimId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    claims: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, bigint, bigint, string, bigint, string] & {policyId: bigint, farmer: string, amount: bigint, status: bigint, metadataHash: string, submittedAt: bigint, rejectionReason: string }],
      'view'
    >
    

    
    clearTriggers: TypedContractMethod<
      [policyId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    createPolicy: TypedContractMethod<
      [name: string, description: string, policyType: BigNumberish, status: BigNumberish, startDate: BigNumberish, endDate: BigNumberish, createdBy: string, payoutRule: SubsidyPayout.PayoutRuleStruct, eligibility: SubsidyPayout.EligibilityStruct, ],
      [bigint],
      'nonpayable'
    >
    

    
    deposit: TypedContractMethod<
      [],
      [void],
      'payable'
    >
    

    
    getClaim: TypedContractMethod<
      [claimId: BigNumberish, ],
      [SubsidyPayout.ClaimStructOutput],
      'view'
    >
    

    
    getPolicy: TypedContractMethod<
      [policyId: BigNumberish, ],
      [SubsidyPayout.PolicyStructOutput],
      'view'
    >
    

    
    getTriggers: TypedContractMethod<
      [policyId: BigNumberish, ],
      [SubsidyPayout.TriggerStructOutput[]],
      'view'
    >
    

    
    nextClaimId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    nextPolicyId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    oracle: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    policies: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, bigint, bigint, bigint, string, SubsidyPayout.PayoutRuleStructOutput, SubsidyPayout.EligibilityStructOutput, bigint] & {name: string, description: string, policyType: bigint, status: bigint, startDate: bigint, endDate: bigint, createdBy: string, payoutRule: SubsidyPayout.PayoutRuleStructOutput, eligibility: SubsidyPayout.EligibilityStructOutput, totalDisbursed: bigint }],
      'view'
    >
    

    
    recordTriggerHit: TypedContractMethod<
      [policyId: BigNumberish, eventId: string, observedValue: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    rejectClaim: TypedContractMethod<
      [claimId: BigNumberish, reason: string, ],
      [void],
      'nonpayable'
    >
    

    
    submitClaim: TypedContractMethod<
      [policyId: BigNumberish, metadataHash: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    updateEligibility: TypedContractMethod<
      [policyId: BigNumberish, eligibility: SubsidyPayout.EligibilityStruct, ],
      [void],
      'nonpayable'
    >
    

    
    updateOracle: TypedContractMethod<
      [newOracle: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateOwner: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updatePayoutRule: TypedContractMethod<
      [policyId: BigNumberish, payoutRule: SubsidyPayout.PayoutRuleStruct, ],
      [void],
      'nonpayable'
    >
    

    
    updatePolicyStatus: TypedContractMethod<
      [policyId: BigNumberish, status: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addTrigger'): TypedContractMethod<
      [policyId: BigNumberish, trigger_: SubsidyPayout.TriggerStruct, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'approveAndPayout'): TypedContractMethod<
      [claimId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claims'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, bigint, bigint, string, bigint, string] & {policyId: bigint, farmer: string, amount: bigint, status: bigint, metadataHash: string, submittedAt: bigint, rejectionReason: string }],
      'view'
    >;
getFunction(nameOrSignature: 'clearTriggers'): TypedContractMethod<
      [policyId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createPolicy'): TypedContractMethod<
      [name: string, description: string, policyType: BigNumberish, status: BigNumberish, startDate: BigNumberish, endDate: BigNumberish, createdBy: string, payoutRule: SubsidyPayout.PayoutRuleStruct, eligibility: SubsidyPayout.EligibilityStruct, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'deposit'): TypedContractMethod<
      [],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'getClaim'): TypedContractMethod<
      [claimId: BigNumberish, ],
      [SubsidyPayout.ClaimStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getPolicy'): TypedContractMethod<
      [policyId: BigNumberish, ],
      [SubsidyPayout.PolicyStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getTriggers'): TypedContractMethod<
      [policyId: BigNumberish, ],
      [SubsidyPayout.TriggerStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'nextClaimId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'nextPolicyId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'oracle'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'policies'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, bigint, bigint, bigint, string, SubsidyPayout.PayoutRuleStructOutput, SubsidyPayout.EligibilityStructOutput, bigint] & {name: string, description: string, policyType: bigint, status: bigint, startDate: bigint, endDate: bigint, createdBy: string, payoutRule: SubsidyPayout.PayoutRuleStructOutput, eligibility: SubsidyPayout.EligibilityStructOutput, totalDisbursed: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'recordTriggerHit'): TypedContractMethod<
      [policyId: BigNumberish, eventId: string, observedValue: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'rejectClaim'): TypedContractMethod<
      [claimId: BigNumberish, reason: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submitClaim'): TypedContractMethod<
      [policyId: BigNumberish, metadataHash: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateEligibility'): TypedContractMethod<
      [policyId: BigNumberish, eligibility: SubsidyPayout.EligibilityStruct, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateOracle'): TypedContractMethod<
      [newOracle: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateOwner'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updatePayoutRule'): TypedContractMethod<
      [policyId: BigNumberish, payoutRule: SubsidyPayout.PayoutRuleStruct, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updatePolicyStatus'): TypedContractMethod<
      [policyId: BigNumberish, status: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ClaimApproved'): TypedContractEvent<ClaimApprovedEvent.InputTuple, ClaimApprovedEvent.OutputTuple, ClaimApprovedEvent.OutputObject>;
getEvent(key: 'ClaimRejected'): TypedContractEvent<ClaimRejectedEvent.InputTuple, ClaimRejectedEvent.OutputTuple, ClaimRejectedEvent.OutputObject>;
getEvent(key: 'ClaimSubmitted'): TypedContractEvent<ClaimSubmittedEvent.InputTuple, ClaimSubmittedEvent.OutputTuple, ClaimSubmittedEvent.OutputObject>;
getEvent(key: 'EligibilityUpdated'): TypedContractEvent<EligibilityUpdatedEvent.InputTuple, EligibilityUpdatedEvent.OutputTuple, EligibilityUpdatedEvent.OutputObject>;
getEvent(key: 'FundsDeposited'): TypedContractEvent<FundsDepositedEvent.InputTuple, FundsDepositedEvent.OutputTuple, FundsDepositedEvent.OutputObject>;
getEvent(key: 'OracleUpdated'): TypedContractEvent<OracleUpdatedEvent.InputTuple, OracleUpdatedEvent.OutputTuple, OracleUpdatedEvent.OutputObject>;
getEvent(key: 'OwnerUpdated'): TypedContractEvent<OwnerUpdatedEvent.InputTuple, OwnerUpdatedEvent.OutputTuple, OwnerUpdatedEvent.OutputObject>;
getEvent(key: 'PolicyCreated'): TypedContractEvent<PolicyCreatedEvent.InputTuple, PolicyCreatedEvent.OutputTuple, PolicyCreatedEvent.OutputObject>;
getEvent(key: 'PolicyStatusUpdated'): TypedContractEvent<PolicyStatusUpdatedEvent.InputTuple, PolicyStatusUpdatedEvent.OutputTuple, PolicyStatusUpdatedEvent.OutputObject>;
getEvent(key: 'PolicyUpdated'): TypedContractEvent<PolicyUpdatedEvent.InputTuple, PolicyUpdatedEvent.OutputTuple, PolicyUpdatedEvent.OutputObject>;
getEvent(key: 'TriggerAdded'): TypedContractEvent<TriggerAddedEvent.InputTuple, TriggerAddedEvent.OutputTuple, TriggerAddedEvent.OutputObject>;
getEvent(key: 'TriggerRecorded'): TypedContractEvent<TriggerRecordedEvent.InputTuple, TriggerRecordedEvent.OutputTuple, TriggerRecordedEvent.OutputObject>;
getEvent(key: 'TriggersCleared'): TypedContractEvent<TriggersClearedEvent.InputTuple, TriggersClearedEvent.OutputTuple, TriggersClearedEvent.OutputObject>;

    filters: {
      
      'ClaimApproved(uint256,uint256,address,uint256)': TypedContractEvent<ClaimApprovedEvent.InputTuple, ClaimApprovedEvent.OutputTuple, ClaimApprovedEvent.OutputObject>;
      ClaimApproved: TypedContractEvent<ClaimApprovedEvent.InputTuple, ClaimApprovedEvent.OutputTuple, ClaimApprovedEvent.OutputObject>;
    

      'ClaimRejected(uint256,uint256,address,string)': TypedContractEvent<ClaimRejectedEvent.InputTuple, ClaimRejectedEvent.OutputTuple, ClaimRejectedEvent.OutputObject>;
      ClaimRejected: TypedContractEvent<ClaimRejectedEvent.InputTuple, ClaimRejectedEvent.OutputTuple, ClaimRejectedEvent.OutputObject>;
    

      'ClaimSubmitted(uint256,uint256,address,uint256,string)': TypedContractEvent<ClaimSubmittedEvent.InputTuple, ClaimSubmittedEvent.OutputTuple, ClaimSubmittedEvent.OutputObject>;
      ClaimSubmitted: TypedContractEvent<ClaimSubmittedEvent.InputTuple, ClaimSubmittedEvent.OutputTuple, ClaimSubmittedEvent.OutputObject>;
    

      'EligibilityUpdated(uint256)': TypedContractEvent<EligibilityUpdatedEvent.InputTuple, EligibilityUpdatedEvent.OutputTuple, EligibilityUpdatedEvent.OutputObject>;
      EligibilityUpdated: TypedContractEvent<EligibilityUpdatedEvent.InputTuple, EligibilityUpdatedEvent.OutputTuple, EligibilityUpdatedEvent.OutputObject>;
    

      'FundsDeposited(address,uint256)': TypedContractEvent<FundsDepositedEvent.InputTuple, FundsDepositedEvent.OutputTuple, FundsDepositedEvent.OutputObject>;
      FundsDeposited: TypedContractEvent<FundsDepositedEvent.InputTuple, FundsDepositedEvent.OutputTuple, FundsDepositedEvent.OutputObject>;
    

      'OracleUpdated(address)': TypedContractEvent<OracleUpdatedEvent.InputTuple, OracleUpdatedEvent.OutputTuple, OracleUpdatedEvent.OutputObject>;
      OracleUpdated: TypedContractEvent<OracleUpdatedEvent.InputTuple, OracleUpdatedEvent.OutputTuple, OracleUpdatedEvent.OutputObject>;
    

      'OwnerUpdated(address)': TypedContractEvent<OwnerUpdatedEvent.InputTuple, OwnerUpdatedEvent.OutputTuple, OwnerUpdatedEvent.OutputObject>;
      OwnerUpdated: TypedContractEvent<OwnerUpdatedEvent.InputTuple, OwnerUpdatedEvent.OutputTuple, OwnerUpdatedEvent.OutputObject>;
    

      'PolicyCreated(uint256,string,uint8,uint8,uint256,uint256,uint256,uint256,uint8,uint8)': TypedContractEvent<PolicyCreatedEvent.InputTuple, PolicyCreatedEvent.OutputTuple, PolicyCreatedEvent.OutputObject>;
      PolicyCreated: TypedContractEvent<PolicyCreatedEvent.InputTuple, PolicyCreatedEvent.OutputTuple, PolicyCreatedEvent.OutputObject>;
    

      'PolicyStatusUpdated(uint256,uint8)': TypedContractEvent<PolicyStatusUpdatedEvent.InputTuple, PolicyStatusUpdatedEvent.OutputTuple, PolicyStatusUpdatedEvent.OutputObject>;
      PolicyStatusUpdated: TypedContractEvent<PolicyStatusUpdatedEvent.InputTuple, PolicyStatusUpdatedEvent.OutputTuple, PolicyStatusUpdatedEvent.OutputObject>;
    

      'PolicyUpdated(uint256,uint256,uint256,uint8,uint8)': TypedContractEvent<PolicyUpdatedEvent.InputTuple, PolicyUpdatedEvent.OutputTuple, PolicyUpdatedEvent.OutputObject>;
      PolicyUpdated: TypedContractEvent<PolicyUpdatedEvent.InputTuple, PolicyUpdatedEvent.OutputTuple, PolicyUpdatedEvent.OutputObject>;
    

      'TriggerAdded(uint256,string,uint8,uint256,uint256,uint8)': TypedContractEvent<TriggerAddedEvent.InputTuple, TriggerAddedEvent.OutputTuple, TriggerAddedEvent.OutputObject>;
      TriggerAdded: TypedContractEvent<TriggerAddedEvent.InputTuple, TriggerAddedEvent.OutputTuple, TriggerAddedEvent.OutputObject>;
    

      'TriggerRecorded(uint256,string,uint256)': TypedContractEvent<TriggerRecordedEvent.InputTuple, TriggerRecordedEvent.OutputTuple, TriggerRecordedEvent.OutputObject>;
      TriggerRecorded: TypedContractEvent<TriggerRecordedEvent.InputTuple, TriggerRecordedEvent.OutputTuple, TriggerRecordedEvent.OutputObject>;
    

      'TriggersCleared(uint256)': TypedContractEvent<TriggersClearedEvent.InputTuple, TriggersClearedEvent.OutputTuple, TriggersClearedEvent.OutputObject>;
      TriggersCleared: TypedContractEvent<TriggersClearedEvent.InputTuple, TriggersClearedEvent.OutputTuple, TriggersClearedEvent.OutputObject>;
    
    };
  }